### PR TITLE
Prepare release

### PR DESCRIPTION
**Pull request by corollari**
- Replaced the current build system with a poetry-based one
- Fixed some things that prevented released (readme wasn't formatted according to warehouse's specs)
- Released the package as `stapler3`
- Updated TODO

### CODE REVIEW

**Comment by hellerbarde** [comment]
I have incorporated all (?) changes from your pull request in separate commits and released a new version. Thank you very much for the effort. It made releasing very simple.

**Comment by hellerbarde** [comment]
Would you mind removing your stapler3 PyPI package. I'm sure it will generate a lot of confusion. I'd be happy to add you as a maintainer for the existing package (and this repository), if you're up for that.

**Comment by corollari** [comment]
Hey! Just removed the stapler3 package, given that this project is active again the reason for it's existence just disappeared.  
I'd also recommend removing the files `setup.py` and `requirements.txt`, as they are redundant now that the build system is based on poetry.

Regarding the idea of becoming a maintainer, I'm up for that.

**Comment by hellerbarde** [comment]
okay, very cool. 

Good point about the setup.py and requirements files. I simply forgot. ;)

**Comment by corollari** [comment]
Closing as this has already been merged

**Pull request closed without merging**
