### PR TITLE
Make python3 compatible

### PR DESCRIPTION
**Pull request by Stebalien**
This version is Python2.7 and Python3 compatible. I noticed you already had a branch but it seems to have fallen behind and makes quite a few stylistic changes as well. Out of curiosity, which versions of python are you trying to target?

### CODE REVIEW

**Comment by hellerbarde** [comment]
That's very kind of you, Thank you! The main reason I haven't rebased and merged my python3 port branch is a lack of tests. I would like to have more test PDFs and so on before I add Python 3 to the supported versions. Unfortunately, it won't be until the end of year that I have time to invest in this project again. So if you still have energy to help and you want to contribute even more, build a few more test cases. :) In any case, I will probably use your branch to merge once I have the tests in place.

**Comment by Stebalien** [comment]
Unfortunately, I'm trying to write my thesis so I can't excuse signing up for any more OSS projects. Sorry.

**Comment by hellerbarde** [comment]
Don't worry, I know how you feel. Not writing a thesis, but deadlines are looming. Good luck with yours!

**Comment by Stebalien** [comment]
Thanks! Good luck yourself.

**Comment by vstoykov** [comment]
Hello guys. I know that more test need to come in order to be 100% sure that some change don't break the code. Still even if there is more test we can't test everything.

For the current changes the only thing that looks not so obvious is `range(end, begin + 1)[::-1]` converted to `range(begin, end - 1, -1)`. But you can still check this very easy in python shell.
Other changes are simply putting brackets around the print's argument and using `as` instead of comma in `except` statement.
There are changes from `file` to `open` and using `with` statement which probably need to be looked closely because there are little reordering of lines, but still changes are not so many.

I'm +1 for accepting this PR without new tests.

P.S. @Stebalien from what I see `stapler` is targeting at least Python 2.7 because of string formatting like `'{}'.format(something)`. This will not work on Python 2.6.
If you think which Python3 versions need to be supported I'm for 3.3+.

**Comment by hellerbarde** [comment]
I don't have time right now to check this out, but is this still also python 2 compatible?

**Comment by maitra** [comment]
I am not sure that this was the only issue in 2016, but PyPDF2 exists in python3. With python2 being EOL'ed, it may be worthwhiile to have this pull request modified or merged, or forked out?

**Comment by klartext** [comment]
2015-11-10: "The main reason I haven't rebased and merged my python3 port branch is a lack of tests. I would like to have more test PDFs and so on before I add Python 3 to the supported versions."

Is this really the main reason?
Looks, that there is rather just a time problem with supporting stapler.
If pdf's for testing are the problem, I could create some pdf-documents.
But only, if it really helps. I don't want to invest time for nothing.

But if it's the main point, that test-pdf's are missing, let me know, how they should look.
I would assume odd and even number of pages and different number of pages.

**Comment by rapgro** [comment]
This seems fixed with recent merge of another branch.

**Pull request closed without merging**
